Repository Schroedinger-Hat/certo, pull requests merged in 2025-07, with the labels that each got.

#11 refactor: Homepage and Project Structure
  src/frontend/app.vue
  src/frontend/assets/svg/csv.vue
  src/frontend/assets/svg/graduation.vue
  src/frontend/assets/svg/plane.vue
  src/frontend/components/base/BaseIcon.vue
  src/frontend/components/home/CsvIllustration.vue
  src/frontend/components/home/GraduationIllustration.vue
  src/frontend/components/home/HomeCardFeature.vue
  src/frontend/components/home/HomeSection.vue
  src/frontend/components/home/HomeTrustees.vue
  src/frontend/components/home/PlaneIllustration.vue
  src/frontend/composables/useHomeContent.ts
  src/frontend/nuxt.config.ts
  src/frontend/package-lock.json
  src/frontend/package.json
  src/frontend/pages/index.vue
Labels: enhancement

#33 chore: add ci/cd for frontend
  .changelogrc
  .github/workflows/create-release.yml
  .github/workflows/frontend-ci.yml
  src/frontend/package-lock.json
  src/frontend/package.json
Labels: frontend

#59 chore: add maintainers section in readme
  README.md
Labels: documentation

#60 refactor: Get Started page
  src/frontend/assets/svg/cloudleft.vue
  src/frontend/assets/svg/cloudright.vue
  src/frontend/components/get-started/CloudsIllustration.vue
  src/frontend/components/get-started/GetStartedList.vue
  src/frontend/components/get-started/GetStartedStepper.vue
  src/frontend/composables/useGetStartedContent.ts
  src/frontend/constants/index.ts
  src/frontend/pages/get-started.vue
Labels: refactor
